## 1.Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arraysCreate an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [2]:
import numpy as np

In [1]:
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


## 2. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives 

In [6]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
b=np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
c=np.ones(10)*5
c

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 3.write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [13]:
x = np.array([[20,31],[12,23]])
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Sum of all elements:
86
Sum of each column:
[32 54]
Sum of each row:
[51 35]


## 4.Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [15]:
x = np.array([[20,31],[12,23]])
y = np.array([[200,31],[12,233]])
add=x+y
add

array([[220,  62],
       [ 24, 256]])

In [16]:
sub=x-y
sub

array([[-180,    0],
       [   0, -210]])

In [17]:
mul=x*y
mul

array([[4000,  961],
       [ 144, 5359]])

In [18]:
div=x/y
div

array([[0.1       , 1.        ],
       [1.        , 0.09871245]])

## 5.Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

In [19]:
a1=np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.)
a1

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [21]:
b1=np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.)
b1

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

## 6.Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels

In [22]:
import pandas as pd

In [24]:
ba=pd.DataFrame({'X': [10,20,30,20,10], 'Y': [10, 20, 30, 20, 10], 'Z': [10, 20, 30, 20, 10]})
ba

X   Y   Z
0  10  10  10
1  20  20  20
2  30  30  30
3  20  20  20
4  10  10  10

## 7.Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [27]:
cba=pd.DataFrame({'name': ['ABi','xyz','vbc','abc','tty'], 'score': [10, 20, 30, 20, 10], 'age': [10, 20, 30, 20, 10]})
cba

name  score  age
0  ABi     10   10
1  xyz     20   20
2  vbc     30   30
3  abc     20   20
4  tty     10   10

In [26]:
a12=cba[['name','score']]
a12

name  score
0  ABi     10
1  xyz     20
2  vbc     30
3  abc     20
4  tty     10

## 8.Write a Pandas program to join the two given dataframes along rows and assign all data.

In [35]:
cba=pd.DataFrame({'name': ['ABi','xyz','vbc','abc','tty'], 'score': [10, 20, 30, 20, 10], 'age': [10, 20, 30, 20, 10]})
cba1=pd.DataFrame({'name': ['aa','bb'], 'score': [10, 20], 'age': [10, 20]})
cba2=pd.concat([cba,cba1])
cba2

name  score  age
0  ABi     10   10
1  xyz     20   20
2  vbc     30   30
3  abc     20   20
4  tty     10   10
0   aa     10   10
1   bb     20   20

## 9.Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [36]:
ca=pd.DataFrame({'name': ['ABi','xyz','vbc','abc','tty'], 'score': [10, 20, 30, 20, 10], 'age': [10, 20, 30, 20, 10]})
ca1=pd.DataFrame({'city': ['chennai','mum','delhi','hyd','mum']})
ca2=pd.concat([ca,ca1])
ca2

name  score   age     city
0  ABi   10.0  10.0      NaN
1  xyz   20.0  20.0      NaN
2  vbc   30.0  30.0      NaN
3  abc   20.0  20.0      NaN
4  tty   10.0  10.0      NaN
0  NaN    NaN   NaN  chennai
1  NaN    NaN   NaN      mum
2  NaN    NaN   NaN    delhi
3  NaN    NaN   NaN      hyd
4  NaN    NaN   NaN      mum

In [37]:
ca2.isna()

name  score    age   city
0  False  False  False   True
1  False  False  False   True
2  False  False  False   True
3  False  False  False   True
4  False  False  False   True
0   True   True   True  False
1   True   True   True  False
2   True   True   True  False
3   True   True   True  False
4   True   True   True  False

In [38]:
ca2.isna().sum()

name     5
score    5
age      5
city     5
dtype: int64